/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package facturador;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.*;
import java.awt.Image;
import java.awt.print.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
        LFolio.setText("Factura: "+Data.getFOLIO());
        LFecha.setText("Fecha: "+Data.getFECHA());
        
        LCP.setText(Data.getCODIGO_POSTAL());
        LNombre.setText(Data.getNOMBRE());
        LRFC.setText(Data.getRFC());
        LDirec.setText(Data.getDIRECCION());
        LEmail.setText(Data.getEMAIL());
        LNacionalidad.setText(Data.getNACIONALIDAD());
        LService.setText(Data.getSERVICIO());
        LCost.setText(Data.getCOSTO());
        LCant.setText(Data.getCANTIDAD());
        LSubt.setText(Data.getSUBTOTAL());
        Ltotal.setText(Data.getTOTAL());
        LComent.setText(Data.getCOMENTARIO());
        //Firma_Cliente.setText("Firma Cliente"/*LNombre.getText()*/);
        parseNumToLetter total = new parseNumToLetter(Ltotal.getText());
        LImport.setText(total.run());
        this.setLocationRelativeTo(null);
        this.setSize(650, 715);
        jButton1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JPfactura = new javax.swing.JPanel();
        LImport = new javax.swing.JLabel();
        Ltotal = new javax.swing.JLabel();
        LSubt = new javax.swing.JLabel();
        LCant = new javax.swing.JLabel();
        LCost = new javax.swing.JLabel();
        LService = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        LNacionalidad = new javax.swing.JLabel();
        LCP = new javax.swing.JLabel();
        LDirec = new javax.swing.JLabel();
        LRFC = new javax.swing.JLabel();
        LNombre = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LblRFC = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LFecha = new javax.swing.JLabel();
        LFolio = new javax.swing.JLabel();
        JLcodigoQR = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LComent = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(612, 810));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 649, -1, -1));

        JPfactura.setPreferredSize(new java.awt.Dimension(612, 792));
        JPfactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LImport.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LImport.setText("Aqui el total pero en letras");
        JPfactura.add(LImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 510, -1));

        Ltotal.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        Ltotal.setText("jLabel1");
        JPfactura.add(Ltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, -1, -1));

        LSubt.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LSubt.setText("jLabel1");
        JPfactura.add(LSubt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 350, -1));

        LCant.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LCant.setText("jLabel1");
        JPfactura.add(LCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 465, 350, -1));

        LCost.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LCost.setText("jLabel1");
        JPfactura.add(LCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 350, -1));

        LService.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LService.setText("jLabel1");
        JPfactura.add(LService, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 415, 350, -1));

        LEmail.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LEmail.setText("jLabel1");
        JPfactura.add(LEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 350, -1));

        LNacionalidad.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LNacionalidad.setText("jLabel1");
        JPfactura.add(LNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 350, -1));

        LCP.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LCP.setText("jLabel1");
        JPfactura.add(LCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 350, -1));

        LDirec.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LDirec.setText("jLabel1");
        JPfactura.add(LDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 350, -1));

        LRFC.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LRFC.setText("jLabel1");
        JPfactura.add(LRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 350, -1));

        LNombre.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LNombre.setText("jLabel1");
        JPfactura.add(LNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 350, -1));

        jLabel20.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel20.setText("Total");
        JPfactura.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, -1, -1));

        jLabel19.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel19.setText("Subtotal");
        JPfactura.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel18.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel18.setText("Cantidad");
        JPfactura.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 465, -1, -1));

        jLabel17.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel17.setText("Costo");
        JPfactura.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel16.setText("Servicio");
        JPfactura.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 415, -1, -1));

        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel15.setText("Correo electronico");
        JPfactura.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel14.setText("Nacionalidad");
        JPfactura.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel11.setText("Codigo Postal");
        JPfactura.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel9.setText("Direccion");
        JPfactura.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        LblRFC.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        LblRFC.setText("RFC");
        JPfactura.add(LblRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        LblNombre.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        LblNombre.setText("Nombre");
        JPfactura.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel12.setText("Cantidad en letras");
        JPfactura.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        LFecha.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        LFecha.setText("fecha");
        JPfactura.add(LFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 150, -1));

        LFolio.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        LFolio.setText("Folio");
        JPfactura.add(LFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, -1));
        JPfactura.add(JLcodigoQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 633, 110, 110));
        ImageIcon image = new ImageIcon(getClass().getResource("/img/qr.jpg"));
        Image imgEscalada = image.getImage().getScaledInstance(110, 110, Image.SCALE_SMOOTH);
        Icon iconoScalado = new ImageIcon(imgEscalada);
        JLcodigoQR.setIcon(iconoScalado);

        jScrollPane2.setBorder(null);

        LComent.setEditable(false);
        LComent.setColumns(20);
        LComent.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        LComent.setLineWrap(true);
        LComent.setRows(5);
        LComent.setBorder(null);
        LComent.setOpaque(false);
        LComent.setPreferredSize(new java.awt.Dimension(370, 100));
        jScrollPane2.setViewportView(LComent);
        LComent.setEditable(false);

        JPfactura.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 380, 110));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Factura_chica.png"))); // NOI18N
        JPfactura.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 612, 792));
        //ImageIcon image3 = new ImageIcon(getClass().getResource("/img/factura.png"));
        //        Image imgEscalada3 = image3.getImage().getScaledInstance(612,792, Image.SCALE_SMOOTH);
        //        Icon iconoScalado3 = new ImageIcon(imgEscalada3);
        //jLabel13.setIcon(iconoScalado3);

        jScrollPane1.setViewportView(JPfactura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 633, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Document document = new Document(PageSize.LETTER);
        PdfWriter writer=null;

        try {
            try {
                writer = PdfWriter.getInstance(document, new FileOutputStream(Data.getFOLIO()+".pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (DocumentException ex) {
            Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
        }

        document.open();
        PdfContentByte cb = writer.getDirectContent();
        PdfTemplate tp = cb.createTemplate(612, 792);
        Graphics2D g2 = tp.createGraphicsShapes(612, 792);
        JPfactura.print(g2);
        g2.dispose();
        cb.addTemplate(tp, 0,0);

        // step 5: we close the document
        document.close();
        JavaMail enviarCorreo = new JavaMail(Data.getFOLIO(), LEmail.getText());
        enviarCorreo.run();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLcodigoQR;
    private javax.swing.JPanel JPfactura;
    private javax.swing.JLabel LCP;
    private javax.swing.JLabel LCant;
    private javax.swing.JTextArea LComent;
    private javax.swing.JLabel LCost;
    private javax.swing.JLabel LDirec;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LFecha;
    private javax.swing.JLabel LFolio;
    private javax.swing.JLabel LImport;
    private javax.swing.JLabel LNacionalidad;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LRFC;
    private javax.swing.JLabel LService;
    private javax.swing.JLabel LSubt;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblRFC;
    private javax.swing.JLabel Ltotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

   
}
